title: Julio Díaz
subtitle: Pagina web personal
description: Pagina personal para usos multiples
url: 'https://jlykos.github.io/'
baseurl: 
urls:
  - text: Sobre mi
    url: about
  - text: Blog
    url: blog
  - text: Galería
    url: galeria
  - text: Contactame
    url: contacto
author_logo: profile.png
author: Julio Díaz
author_bio: >-
  Soy estudiante de la carrera Ingeniería Mecatrónica en la Universidad
  Nacional Experimental Politécnica "Antonio José de Sucre". Soy miembro activo
  del Club de Investigación e Innovación Mecatrónica (CIIM) y formé parte del
  Sistema Nacional de Orquestas y Coros Juveniles e Infantiles de Venezuela por
  más de 10 años. En la actualidad dicto cursos de distintas áreas y niveles.
author_email: juliocdiazo41@gmail.com
author_location: Venezuela
author_website_url: 'http://jlykos.github.io/plantilla-cv'
author_website_url_text: CV
typewrite-text: No conocemos una millonésima parte del uno por ciento de nada.
home_slider:
  - logo: Analista_de_datos.png
    title: Analista de datos
    url: /assets/img/certificados/Analista_de_datos.png
    visibility: true
  - logo: desarrollador_de_videojuegos.pngg
    title: Desarrollador de videojuegos
    url: /assets/img/certificados/desarrollador_de_videojuegos.png
    visibility: true
  - logo: tecnico_en_mineria_de_datos.png
    title: Tecnico en mineria de datos
    url: /assets/img/certificados/tecnico_en_mineria_de_datos.png
    visibility: true
  - logo: Introduccion-al-desarrollo-web-II.png
    title: Introduccion al desarrollo web II
    url: /assets/img/certificados/Introduccion-al-desarrollo-web-II.png
    visibility: true
  - logo: Introduccion-al-desarrollo-web-I.png
    title: Introduccion al desarrollo web I
    url: /assets/img/certificados/Introduccion-al-desarrollo-web-I.png
    visibility: true
  - logo: Ciberseguridad-en-el-teletrabajo.png
    title: Ciberseguridad en el teletrabajo
    url: /assets/img/certificados/Ciberseguridad-en-el-teletrabajo.png
    visibility: true
  - logo: Ingles_basico_conversacional_networking.png
    title: Ingles basico - conversacional y networking
    url: https://courses.edx.org/certificates/06c2aecc09684b0a9393f059c6c05870
    visibility: true
  - logo: Wordpress-basico.png
    title: Wordpress básico
    url: https://jlykos.github.io/assets/img/certificados/Wordpress-basico.png
    visibility: true
  - logo: sistema-riego-arduino.jpg
    title: Sistema de riego automático con arduino
    url: https://www.udemy.com/certificate/UC-aba7d99e-5e08-47db-bcd7-d9db09947c20/
    visibility: true
  - logo: analisis-y-diseño-de-circuitos.jpg
    title: Ingenieria Electronica - Analisis Y Diseño De Circuitos I
    url: https://www.udemy.com/certificate/UC-f2fecdcd-25ef-4d50-9839-afb590dd9c27/
    visibility: true
  - logo: introduccion-a-git-y-github.jpg
    title: Introduccion a Git y Github
    url: https://www.udemy.com/certificate/UC-bcfb0835-5ada-4f85-8f81-80785625a05c/
    visibility: true
author_work_experiences:
  - company_name: Autonomo
    company_logo: profile.png
    company_url: 'https://jlykos.github.io'
    designation: Presidente
    description: null
    visibility: true
  - company_name: UNEXPO
    company_logo: UNEXPO.png
    company_url: 'http://www.unexpo.edu.ve/'
    designation: Ayudante Técnico de laboratorio
    description: null
    visibility: true
  - company_name: Fundación Musical Simón Bolívar
    company_logo: FUNDAMUSICAL.png
    company_url: 'https://fundamusical.org.ve/'
    designation: Tallerista
    description: Teoría musical y orquesta de flauta dulce con niños entre 5 y 13 años.
    visibility: true
author_education_details:
  - college_logo: UNEXPO.png
    college_name: Universidad Nacional Experimental Politécnica "Antonio José de Sucre"
    college_url: 'http://www.unexpo.edu.ve/'
    college_degree: Ingeniero
    description: Ingeniería Mecatrónica
    visibility: true
  - college_logo: fundauc.gif
    college_name: Fundación Universidad de Carabobo
    college_url: 'http://www.uc.edu.ve/univ_dep_fundauc.php'
    college_degree: Aprobación
    description: 8vo libro
    visibility: true
author_project_details:
  - project_thumbnail: SAMI.png
    project_title: S.A.M.I.
    project_description: >-
      Sistema de Asistencia Médica Integral con módulos según requisitos de uso interno para la Fundación Manos de Gracia.
    project_url: ''
    url_text: De uso interno
    visibility: true
  - project_thumbnail: Llenadora.png
    project_title: Sistema de llenado
    project_description: >-
      Sistema con banda transportadora para el llenado automático de envases
      según configuración inicial mediante interfaz simple.
    project_url: https://www.youtube.com/watch?v=qcPdu4HSLWw
    url_text: Video
    visibility: true
  - project_thumbnail: SOFIA.png
    project_title: S.O.F.I.A.
    project_description: Solo Otra Funcional Inteligencia Artificial para uso personal.
    project_url: 'https://t.me/SOFIA_justmybot'
    url_text: Chat
    visibility: true
  - project_thumbnail: Baymax.png
    project_title: Baymax.app
    project_description: >-
      Asistente medico personal para la dosificacion y dispensacion de farmacos
      solidos a personas de la tercera edad.
    project_url: ''
    url_text: 
    visibility: true
  - project_thumbnail: SIQRU.png
    project_title: SIQRU
    project_description: >-
      Sistema de Identificación por QR para Universidades desarrollado para la
      UNEXPO en su actividad de Universidades Innovan llevada a cabo por StartUp
      Venezuela
    project_url: ''
    url_text: 
    visibility: true
twitter_username: julio37diaz
github_username: JLykos
facebook_username: DarthStark
linkedin_username: juliodiazortiz
behance_username: null
instagram_username: julio37diaz
medium_username: null
telegram_username: DarthStark
dribbble_username: null
flickr_username: null
hyvor_talk_website_id: 922
wakatime_username: DarthStark
tusclases_perfil: false
tusclases_reputacion: false
mailchimp_form_url: >-
  https://github.us10.list-manage.com/subscribe?u=a5c14477d27cdfe64716c5d98&id=3dc178ea35
formspree_email: julioortiz01@hotmail.com
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_home_slider: true
algolia:
  application_id: WW46ZH3SF2
  index_name: blog_post
  files_to_exclude: []
  nodes_to_index: article
  search_only_api_key: b4c88d9daed0eeb88d1e59436c5a63a9
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  - products
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: _site
